Graphql
TheRealJackiBoi/FullStackExam-Frontend pull request #17
Opened 2024-03-15 13:43 UTC by Juliuslassen

graphql for booking and company

2024-03-15 16:39 UTC, TheRealJackiBoi commented on src/graphql/company/companyQueries.ts
> +export const getCompanyByID = gql`
Har også lavet en, hva gør vi?

2024-03-15 16:43 UTC, TheRealJackiBoi requested changes

2024-03-15 16:43 UTC, TheRealJackiBoi commented on src/graphql/company/companyMutation.ts
> +  mutation Mutation($name: String!, $description: String!, $zipCode: Int!, $street: String!, $houseNumber: Int!, $companyOwnerId: ID!, $token: String!) {
Navne skal passe til dem anders har lavet underscore og all caps

2024-03-15 16:43 UTC, TheRealJackiBoi commented on src/graphql/company/companyQueries.ts
> +    companies {
navn

2024-03-15 16:43 UTC, TheRealJackiBoi commented on src/graphql/booking/bookingMutations.ts
> +export const createBooking = gql`
navne

2024-03-15 16:43 UTC, TheRealJackiBoi commented on src/graphql/booking/bookingQueries.ts
> +export const getBookingByID = gql`
navne

2024-03-15 16:44 UTC, TheRealJackiBoi requested changes
Ser fino ud, navnene skal bare være allcaps og med underscore

2024-03-15 21:09 UTC, Juliuslassen commented on src/graphql/company/companyQueries.ts
> +export const getCompanyByID = gql`
Vi må vel se på det når vi merger?

2024-03-16 15:57 UTC, HeinLarsen approved these changes

2024-03-16 16:00 UTC, HeinLarsen approved these changes

2024-03-17 10:13 UTC, closed without merging